language: node_js
node_js:
 - "4.4.7"
sudo: false
before_install:
- npm install -g grunt-cli
- git config --global user.name "Travis CI"
- git config --global user.email "travis@travis-ci.org"
- git remote add origin_ssh git@github.com:alphagov/govuk_elements.git
- openssl aes-256-cbc -K $encrypted_85ebe8034b89_key -iv $encrypted_85ebe8034b89_iv -in .travis/govuk_elements.enc -out ~/.ssh/id_rsa -d && chmod 600 ~/.ssh/id_rsa
- ls -al ~/.ssh
- head -1 ~/.ssh/id_rsa
- tail -1 ~/.ssh/id_rsa
- ssh git@github.com || true
-  # This openssl command was generated automatically by `travis encrypt-file`, see `.travis/README.md` for more details
install:
- npm install
script:
- npm test
notifications:
  email: false
before_deploy:
- test $TRAVIS_TEST_RESULT = 0
deploy:
- provider: npm
  api_key:
    secure: VAHPK3W0YVWqx03j659FbKjvEwd+UIDfb1x55to9u+PzyVqQp1CXalsYuKQSavxqInaV3gzNJpbANo6SIXlpAUxZPChiTk0rJwUhz7u1fRY0Lshb+aDOMnXSfjSqiIGThNRpjYdxBiJsnrYP1T6unHuo2A1K8mXjwdFtxhadh+w=
  email: govuk-dev@digital.cabinet-office.gov.uk
  on:
    tags: true
    all_branches: true
after_deploy:
- provider: script
  script: './push-version-tag.sh'
  on:
    all_branches: true
- provider: script
  script: "./update-release-branch.sh"
  on:
    tags: true
    all_branches: true
env:
  global:
    secure: eFtS+dlf00c3h4Rpp1FSZw6wOmZPmY4lYbqPV6MQa+VUgh+FRbUYOjDJP3UFaTsWNxMIL4mhEKFYLnkVftBdz1FgPjhIO3jNXleGMgVVedtD+qo5hTu1KI39t68K2YcELx9+kzeccX77WVmv/qJTVg7+f84WP9ebzVOJCQprJuw=
